version: '3.7'

# Define named volumes
volumes:
  nexinx_postgres_data:
  rabbitmq_data:

# Define custom networks
networks:
  nexinx-net:
    driver: bridge

services:
  # ###############################################
  # PostgreSQL Database
  # ###############################################
  nexinx-database:
    container_name: nexinx-database
    image: postgres:latest
    environment:
      #PGDATA: /data/postgres
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: psql
      PGDATA: /data/nexinx_dev_db_001
      DB_USER: nexinx_dev_user
      DB_PASSWORD: nexinx_dev_password
    volumes:
      - nexinx_postgres_data:/data/nexinx_dev_db_001
      - ./nexinx-api/database/nexinx-api/database/V1.0.0__createAllTables.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nexinx-net
    ports:
      - 5432:5432
    # restart: unless-stopped
  ###############################################
  # RabbitMQ-Config
  ###############################################
  nexinx-rabbitmq:
    container_name: nexinx-rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
      - "1883:1883"   # MQTT port
      - "8883:8883"   # MQTT over SSL port
    environment:
      RABBITMQ_DEFAULT_USER: mq_user
      RABBITMQ_DEFAULT_PASS: mq_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_management &&
             rabbitmq-server"
    networks:
      - nexinx-net
  # ###############################################
  # Nexinx API (Backend)
  # ###############################################
  nexinx-api:
    container_name: nexinx-api
    image: nexinx-api:latest 
    build:
      context: ./nexinx-api
      dockerfile: Dockerfile.jvm
    ports:
      - 8080:8080
    networks:
      - nexinx-net
    depends_on:
      - nexinx-database
    environment:
      # DB Settings     
      DB_USER: nexinx_dev_user
      DB_PASSWORD: nexinx_dev_password
      DB_NAME: nexinx_dev_db_001
      DB_SERVER: nexinx-database
      DB_PORT: '5432'
      # JWT Settings
      JWT_ISSUER: 'http://localhost:8080'
      CORS_ORIGINS: 'http://localhost'
  # ###############################################
  # Nginx Webserver & Nexinx-UI
  # ###############################################
  nexinx-webui:
    container_name: nexinx-webui
    image: nexinx-webui:latest
    build:
      context: ./nexinx-webui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - nexinx-net
    restart: always
    depends_on:
      - nexinx-database

  ###############################################
  # Pg-Aadmin
  ###############################################
  pgadmin:
    container_name: nexinx-pg-admin
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - nexinx-net
    depends_on:
      - nexinx-database
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"